using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerCheckPoint : MonoBehaviour
{
    [SerializeField] GameObject player;
    [SerializeField] List<GameObject> checkPoints;
    [SerializeField] Vector3 vectorPoint;
    private int checkpointCount = 1;

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.R))
        {
            player.transform.position = vectorPoint;
            this.gameObject.transform.rotation = Quaternion.Euler(0,0,0);
            this.gameObject.GetComponent<Rigidbody>().Sleep();
        }

    }
    private void OnTriggerEnter(Collider other)
    {
        vectorPoint=player.transform.position;
        Destroy(other.gameObject);
    }

}
